spring:
  application:
    name: cloud-zuul
  zipkin:
    base-url: http://localhost:8040
  sleuth:
    sampler:
      percentage: 1

server:
  port: 8050

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

integration:
  provider:
    greeting-provider: greeting-service

# zuul 默认以服务名做映射
zuul:
  host:
    max-total-connections: 500
    max-per-route-connections: 50
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  ribbon-isolation-strategy: THREAD
  prefix: /api
  ignored-services: '*'
  routes:
    greeting-service: /greeting-service/**
    customer-service:
      path: /customer-service/**
      serviceId: customer-service
      sensitiveHeaders:

ribbon:
  read-timeout: 10000
  connect-timeout: 10000
  max-auto-retries: 0
  max-auto-retries-next-server: 1
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 10

# export internal endpoints for external request
management:
  security:
    enabled: false


