spring:
  application:
    name: customer-service
  zipkin:
    base-url: http://localhost:8040
server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
