spring:
  application:
    name: eureka-server
server:
  port: 8080
eureka:
  instance:
    hostname: localhost:8080
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
